# Site settings
title: IT в Казахстане
email: gmegido@gmail.com
description: >
 made by engineers for future engineers
baseurl: ""
url: "http://kzit.netlify.com/"
enable_retina: false
permalink: :title
nav_list:
  Home : ['Главная', '/', 'fa-home']
  About : ['О проекте', '/about', 'fa-anchor']
  #Contact : ['Contact', '/contact', 'fa-plane']
  #Author : ['Author', '/author/michelle', 'fa-user']
single_footer: '<p>Made by developers for developers. #KZIT &copy; 2017 <a href="/">latest posts</a></p>'
footer_links:
    About: ['О проекте', '/about']
    #Writer: ['Writer 2016', '/about']


# Build settings
# markdown: kramdown
